encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "wikip"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.title, name="title"),
    path("/serch", views.search, name="search"),
    path("/new", views.newtab, name="newtab"),
    path("/", views.ranpage, name="random"),
    path("/Edit", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from . import util
from markdown2 import markdown
import random
import json
import os
p = """<form action="{% url 'wikip:edit' %}" method="GET">
    {% csrf_token %}
    <div style = " margin-top: 50px;">
    <input type="text" value="{{ name }}" hidden name="pretitle">
    <input type="submit" value="Edit" class="btn btn-dark">
    </div>
</form>"""
p1 = "{{ name }}"


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),

    })


def title(request, title):
    f = util.get_entry(title)
    if f != None:
        return render(request, f"entrieshtml/{title}.html", {
            "title": util.get_entry(title),
            "name": title,

        })
    else:
        return render(request, "encyclopedia/error.html", {
            "error_text": f"There is no such entries as {title}",

        })


def search(request):
    f = util.list_entries()
    title = request.GET.get('q')
    count = 0
    if request.method == "GET":
        for entry in f:
            if entry.upper() == title.upper():
                return render(request, f"entrieshtml/{title}.html", {
                    "title": util.get_entry(entry),
                    "name": entry,

                })
            else:
                for keyword in title:
                    for enter in f:
                        for key in enter:
                            if keyword.upper() == key.upper():
                                return render(request, "encyclopedia/keyword_match.html", {
                                    "name": enter
                                })
                                count += 1
                            else:
                                break
                    if count == 0:
                        return render(request, "encyclopedia/error.html", {
                            "error_text": f"no such entry as {title}",

                        })
    else:
        return render(request, "encyclopedia/error.html", {
            "error_text": f"Error 403 invalid method",

        })


def newtab(request, method=["POST"]):
    ''' i did't use util.save_entry, i actually forgot it was there orignaly, i found it after i wrote this code of my own, hope its okay '''

    if request.method == "POST":
        titles = request.POST.get('entry_name')
        content = request.POST.get('content')

        if os.path.exists(f'C:/Users/erfan/Desktop/Mozzie-atles/encyclopedia/templates/entrieshtml/{titles}.html'):
            return render(request, "encyclopedia/newtab.html", {
                "xin": 1
            })
        else:
            ali = f"\n{content}"
            with open(f'entries/{titles}.md', 'w') as f:
                f.write(ali)

            filepath = os.path.join(
                'C:/Users/erfan/Desktop/Mozzie-atles/encyclopedia/templates/entrieshtml', f'{titles}.html')

            with open(filepath, 'w') as f:
                x = markdown(ali)
                cheat = ["{% extends 'encyclopedia/layout.html' %}",
                         "{% block title %}", "{% endblock %}", "{% block body %}", p, p1]
                f.write(cheat[0])
                f.write(cheat[1])
                f.write(titles)
                f.write(cheat[2])
                f.write(cheat[3])
                f.write(x)
                f.write(p)
                f.write(cheat[2])

                """ for import layout.html in to the new file """
            return render(request, f"entrieshtml/{titles}.html")
    return render(request, "encyclopedia/newtab.html")


def ranpage(request):
    lists = []
    for f in util.list_entries():
        lists.append(f)
    page = random.choice(lists)
    return render(request, f"entrieshtml/{page}.html", {
        "title": page
    })


def edit(request):
    titles = request.POST.get('titles')
    content = request.POST.get('content')
    pretitle = request.GET.get('pretitle')
    if request.method == "GET":
        with open(f"entries/{pretitle}.md", 'r') as f:
            if f.mode == 'r':
                precontent = f.read()

    if request.method == "POST":
        with open(f'entries/{titles}.md', 'w') as f:
            f.write(content)

        filepath = os.path.join(
            'C:/Users/erfan/Desktop/Mozzie-atles/encyclopedia/templates/entrieshtml', f'{titles}.html')
        with open(filepath, 'w') as f:
            x = markdown(content)
            cheat = ["{% extends 'encyclopedia/layout.html' %}",
                     "{% block title %}", "{% endblock %}", "{% block body %}", p, p1]
            f.write(cheat[0])
            f.write(cheat[1])
            f.write(p1)
            f.write(cheat[2])
            f.write(cheat[3])
            f.write(x)
            f.write(p)
            f.write(cheat[2])

            """ for import layout.html in to the new file """
        return render(request, f"entrieshtml/{titles}.html", {
            "name": titles
        })
    return render(request, "encyclopedia/edit.html", {
        "precontent": precontent,
        "pretitle": pretitle
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit wiki
{% endblock %}

{% block body %}
<div>
    <form action="{% url 'wikip:edit' %}" method="POST">
        {% csrf_token %}
        <div style="margin-bottom: 10px;">

            <input name="titles" type="text" value="{{ pretitle }}"> 
        </div>
        <div>

            <textarea name="content" cols="10" rows="10"
                placeholder="Eddit content for this wiki">{{ precontent }}</textarea>
        </div>
        <div>
            {% if xin == 1 %}
            <div class="alert alert-primary" role="alert">
                This entry already exists
            </div>
            {% endif %}
            <input type="submit" class="btn btn-dark" value="Save">
        </div>
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error 404

{% endblock %}

{% block body %}
<h1> Error 404 </h1>
<div>
    {{ error_text }}
</div>


{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <a href="{{ entry }}">
        <li>{{ entry }}</li>
    </a>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/keyword_match.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>Search results</h1>

<ul>

    <a href="{{name}}">
        <li>{{ name }}</li>
    </a>

</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'wikip:search' %}" method="GET">
                {% csrf_token %}
                <input class=" search" type="text" name="q" placeholder="Search Encyclopedia">


            </form>
            <div>
                <a href="{% url 'wikip:index' %}">Home</a>
            </div>
            <div>


                <a href="{% url 'wikip:newtab' %}">Create New Page</a>

            </div>
            <div>
                <a href="{% url 'wikip:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/newtab.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New wiki
{% endblock %}

{% block body %}
<div>
    <form action="{% url 'wikip:newtab' %}" method="POST">
        {% csrf_token %}
        <div style="margin-bottom: 10px;">

            <input name="entry_name" type="text" placeholder="Enter new title">
        </div>
        <div>

            <textarea name="content" id="" cols="30" rows="10"
                placeholder="Enter Marcdown content for your wiki"></textarea>
        </div>
        <div>
            {% if xin == 1 %}
            <div class="alert alert-primary" role="alert">
                This entry already exists
            </div>
            {% endif %}
            <input type="submit" class="btn btn-dark">
        </div>
    </form>
</div>

{% endblock %}

encyclopedia/templates/entrieshtml/CSS.html
{% extends 'encyclopedia/layout.html' %}{% block title %}{{ name }}{% endblock %}{% block body %}<h1>foo</h1>
<form action="{% url 'wikip:edit' %}" method="GET">
    {% csrf_token %}
    <div style = " margin-top: 50px;">
    <input type="text" value="{{ name }}" hidden name="pretitle">
    <input type="submit" value="Edit" class="btn btn-dark">
    </div>
</form>{% endblock %}

encyclopedia/templates/entrieshtml/Django.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ name }}

{% endblock %}

{% block body %}
<h1>Django</h1>
<p>Django is a web framework written using <a href="/Python">Python</a> that allows for the design of web applications that generate <a href="/HTML">HTML</a> dynamically.</p>

<form action="{% url 'wikip:edit' %}" method="POST">
    {% csrf_token %}
    <div style="margin-top: 50px;">
        <input type="text" value="{{ name }}" hidden name="title">
        <input type="submit" value="Edit" class="btn btn-dark">
    </div>
</form>

{% endblock %}

encyclopedia/templates/entrieshtml/Git.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{name}}
{% endblock %}

{% block body %}
<h1 id="git">Git</h1>
<p>Git is a version control tool that can be used to keep track of versions of a software project.</p>
<h2 id="github">GitHub</h2>
<p>GitHub is an online service for hosting git repositories.</p>

<div style="margin-top: 50px;">
    <a href="" role="button" class="btn btn-dark ">Eddit</a>
</div>


{% endblock %}

encyclopedia/templates/entrieshtml/HTML.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ name }}

{% endblock %}

{% block body %}
<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li>headings</li>
<li>paragraphs</li>
<li>lists</li>
<li>links</li>
<li>and more!</li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
<div style="margin-top: 50px;">
    <a href="" role="button" class="btn btn-dark ">Eddit</a>
</div>

{% endblock %}

encyclopedia/templates/entrieshtml/Python.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{name}}
{% endblock %}

{% block body %}

<h1 id="python">Python</h1>
<p>Python is a programming language that can be used both for writing <strong>command-line scripts</strong> or building <strong>web applications</strong>.</p>
<div style="margin-top: 50px;">
    <a href="" role="button" class="btn btn-dark ">Eddit</a>
</div>

{% endblock %}

encyclopedia/templates/entrieshtml/Uyghurs.html
{% extends 'encyclopedia/layout.html' %}{% block title %}Uyghurs{% endblock %}{% block body %}<h1>Uyghurs</h1>

<p>The Uyghurs ,alternately Uygurs, Uighurs or Uigurs, are a Turkic-speaking minority ethnic group originating from and culturally affiliated with the general region of Central and East Asia. The Uyghurs are recognized as native to the Xinjiang Uyghur Autonomous Region in Northwest China. .</p>
<div style="margin-top: 50px;">
    <a href="" role="button" class="btn btn-dark ">Eddit</a>
</div>

{% endblock %}

encyclopedia/templates/entrieshtml/xxxtentacion.html
{% extends 'encyclopedia/layout.html' %}{% block title %}{{ name }}{% endblock %}{% block body %}<h1>xxxtentacion</h1>

<p>xxxtentacion is a rapper from florida , sadly he passed away at the age of 20</p>
<form action="{% url 'wikip:edit' %}" method="GET">
    {% csrf_token %}
    <div style = " margin-top: 50px;">
    <input type="text" value="{{ name }}" hidden name="pretitle">
    <input type="submit" value="Edit" class="btn btn-dark">
    </div>
</form>{% endblock %}